/*
* Shifra Schectman
* Lab 2 Makefile
* April 15, 2018
* This program counts the letters in a file and outputs it 
*/
all: letterCount

output: main.o 
	g++ main.o -o output

main.o: main.cpp
	g++ -c main.cpp

clean:
	rm *o letterCount

